name: intelliface
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.6                     # ✅ added for face recognition
  google_mlkit_face_detection: ^0.13.1  # ✅ added for face recognition
  typed_data: ^1.3.2
  path_provider: ^2.1.2                 # ✅ helper for file paths
  path: ^1.9.0                          # ✅ helper for file paths
  vibration: ^1.8.0
  assets_audio_player: ^3.0.8    # ✅ correct latest release
  fluttertoast: ^8.2.2
  intl: ^0.19.0  # ✅ Add this line
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.1.0
  image: ^4.0.17  # For cropping the image
  http: ^1.1.0
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  geolocator: ^10.1.0
  google_mlkit_commons: ^0.11.0
  
  
  

  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  
flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icon.png
    - assets/sounds/success.mp3
